// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_EVWl4yFClGFakdAGedK03ISHGLLRSDc',
    appId: '1:461429969883:web:650bd6c0f1af56c7c4cdfe',
    messagingSenderId: '461429969883',
    projectId: 'wooju-study-library',
    authDomain: 'wooju-study-library.firebaseapp.com',
    storageBucket: 'wooju-study-library.firebasestorage.app',
    measurementId: 'G-GM4G7KF2S6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg-cr5R_4jhfZ32w9A_epUCZvkAckWnWw',
    appId: '1:461429969883:android:e165b13e77c9b53ec4cdfe',
    messagingSenderId: '461429969883',
    projectId: 'wooju-study-library',
    storageBucket: 'wooju-study-library.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuoAcC5JTaApNNuBwNCTiItM1XyzMOaIU',
    appId: '1:461429969883:ios:24ce3a13134c123cc4cdfe',
    messagingSenderId: '461429969883',
    projectId: 'wooju-study-library',
    storageBucket: 'wooju-study-library.firebasestorage.app',
    iosBundleId: 'com.example.woojuStudyLibrary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuoAcC5JTaApNNuBwNCTiItM1XyzMOaIU',
    appId: '1:461429969883:ios:24ce3a13134c123cc4cdfe',
    messagingSenderId: '461429969883',
    projectId: 'wooju-study-library',
    storageBucket: 'wooju-study-library.firebasestorage.app',
    iosBundleId: 'com.example.woojuStudyLibrary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_EVWl4yFClGFakdAGedK03ISHGLLRSDc',
    appId: '1:461429969883:web:dc8f7e325e1ec2b4c4cdfe',
    messagingSenderId: '461429969883',
    projectId: 'wooju-study-library',
    authDomain: 'wooju-study-library.firebaseapp.com',
    storageBucket: 'wooju-study-library.firebasestorage.app',
    measurementId: 'G-20162BNXZ1',
  );

}